// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: headers.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MIMEHeaders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Headers map[string]string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MIMEHeaders) Reset() {
	*x = MIMEHeaders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_headers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MIMEHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MIMEHeaders) ProtoMessage() {}

func (x *MIMEHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_headers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MIMEHeaders.ProtoReflect.Descriptor instead.
func (*MIMEHeaders) Descriptor() ([]byte, []int) {
	return file_headers_proto_rawDescGZIP(), []int{0}
}

func (x *MIMEHeaders) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_headers_proto protoreflect.FileDescriptor

var file_headers_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x83, 0x01, 0x0a, 0x0b, 0x4d, 0x49, 0x4d, 0x45, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x38, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4d, 0x49,
	0x4d, 0x45, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x1a,
	0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_headers_proto_rawDescOnce sync.Once
	file_headers_proto_rawDescData = file_headers_proto_rawDesc
)

func file_headers_proto_rawDescGZIP() []byte {
	file_headers_proto_rawDescOnce.Do(func() {
		file_headers_proto_rawDescData = protoimpl.X.CompressGZIP(file_headers_proto_rawDescData)
	})
	return file_headers_proto_rawDescData
}

var file_headers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_headers_proto_goTypes = []any{
	(*MIMEHeaders)(nil), // 0: main.MIMEHeaders
	nil,                 // 1: main.MIMEHeaders.HeadersEntry
}
var file_headers_proto_depIdxs = []int32{
	1, // 0: main.MIMEHeaders.headers:type_name -> main.MIMEHeaders.HeadersEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_headers_proto_init() }
func file_headers_proto_init() {
	if File_headers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_headers_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MIMEHeaders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_headers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_headers_proto_goTypes,
		DependencyIndexes: file_headers_proto_depIdxs,
		MessageInfos:      file_headers_proto_msgTypes,
	}.Build()
	File_headers_proto = out.File
	file_headers_proto_rawDesc = nil
	file_headers_proto_goTypes = nil
	file_headers_proto_depIdxs = nil
}
